export const people = [
  {
    key: 1,
    name: "Reginauld Heckner",
    rating: 3,
    gender: "Male",
    job: "Senior Developer",
    city: "Leiden",
  },
  {
    key: 2,
    name: "Glyn Deackes",
    rating: 4,
    gender: "Female",
    job: "Quality Control Specialist",
    city: "‘Akko",
  },
  {
    key: 3,
    name: "Jordan Pearlman",
    rating: 4,
    gender: "Female",
    job: "Librarian",
    city: "Červená Voda",
  },
  {
    key: 4,
    name: "Sabine Kemell",
    rating: 3,
    gender: "Female",
    job: "Analog Circuit Design manager",
    city: "Telč",
  },
  {
    key: 5,
    name: "Yehudit Wenn",
    rating: 4,
    gender: "Male",
    job: "Developer I",
    city: "Fiorentino",
  },
  {
    key: 6,
    name: "Dewain Sambedge",
    rating: 1,
    gender: "Male",
    job: "Actuary",
    city: "Huyunxiang",
  },
  {
    key: 7,
    name: "Jerrome Conville",
    rating: 3,
    gender: "Bigender",
    job: "Associate Professor",
    city: "Ōzu",
  },
  {
    key: 8,
    name: "Bev Dupey",
    rating: 1,
    gender: "Female",
    job: "Research Associate",
    city: "Cikawung",
  },
  {
    key: 9,
    name: "Eldredge Dimmer",
    rating: 4,
    gender: "Male",
    job: "Web Developer II",
    city: "Yancheng",
  },
  {
    key: 10,
    name: "Lauri Aberchirder",
    rating: 3,
    gender: "Female",
    job: "Human Resources Assistant IV",
    city: "Miskindzha",
  },
  {
    key: 11,
    name: "Spike Mazzey",
    rating: 2,
    gender: "Male",
    job: "Chief Design Engineer",
    city: "Kristianstad",
  },
  {
    key: 12,
    name: "Natka Semechik",
    rating: 4,
    gender: "Female",
    job: "Speech Pathologist",
    city: "Itinga",
  },
  {
    key: 13,
    name: "Izaak Wildman",
    rating: 3,
    gender: "Male",
    job: "Business Systems Development Analyst",
    city: "Chaiyaphum",
  },
  {
    key: 14,
    name: "Berton Sancias",
    rating: 4,
    gender: "Non-binary",
    job: "Electrical Engineer",
    city: "San Pedro Ayampuc",
  },
  {
    key: 15,
    name: "Trisha Snewin",
    rating: 1,
    gender: "Female",
    job: "Assistant Media Planner",
    city: "Guruyan",
  },
  {
    key: 16,
    name: "Augustine O'Hickey",
    rating: 2,
    gender: "Male",
    job: "Senior Quality Engineer",
    city: "Goianira",
  },
  {
    key: 17,
    name: "Yelena Zmitrovich",
    rating: 2,
    gender: "Female",
    job: "Help Desk Technician",
    city: "Nanjiao",
  },
  {
    key: 18,
    name: "Bertha McIleen",
    rating: 2,
    gender: "Female",
    job: "Accounting Assistant I",
    city: "Nowshera",
  },
  {
    key: 19,
    name: "Artemas Foan",
    rating: 4,
    gender: "Male",
    job: "Media Manager IV",
    city: "Karangtalun",
  },
  {
    key: 20,
    name: "Arthur Wareing",
    rating: 4,
    gender: "Male",
    job: "Food Chemist",
    city: "Benito Juarez",
  },
];
